language: node_js
node_js:
    - "12"
services:
  - docker
before_install:
  - npm install
script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nearygy/yinguangyao.github.io:latest .
  - docker push nearygy/yinguangyao.github.io:latest